set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set ruler
set history=50
set showcmd
set incsearch

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

syntax on
set hlsearch

filetype plugin indent on

augroup vimrc
  au!
  autocmd FileType text setlocal textwidth=78
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
augroup END

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif


colorscheme molokai
set number
set expandtab
set tabstop=4
set softtabstop=4
set showmatch
set cursorline
set shiftwidth=4
set smartindent
set smarttab                  " tab and backspace are smart
set ignorecase
set hidden
set directory=~/.vim/tmp

" powerline configuration
let s:powerline_path = glob('$HOME/.local/lib/python*/site-packages/powerline/bindings/vim/')
if !empty(s:powerline_path)
  let &rtp .= ',' . s:powerline_path
endif
let g:Powerline_symbols = 'fancy'
set t_Co=256
set laststatus=2
set showtabline=2

