# tmux autostart
# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec tmux


alias lt='ls -lrta'
alias ..='cd ..'
alias ...='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

alias phpunit='vendor/bin/phpunit'

# Force git langage
export LANGUAGE='en_US.UTF-8 git'

