set number       " display line number
set expandtab    " converts tabs to spaces
set autoindent   " automatically copy indentation from previous line
set smartindent  " indents one extra level according to current syntax


set list         " displaty whitespaces
set ruler

set ignorecase   " Case-insensitive searching.
set smartcase    " But case-sensitive if expression contains a capital letter.
set tabstop=4    " how many columns a tab counts for
set shiftwidth=4 " how many columns text is indented with the reindent operations

set incsearch    " Highlight matches as you type.
set hlsearch     " Highlight matches.
set showmatch    " Show matching (){}[]

set cursorline   " Highlight current line

" activate the mouse
" set mouse=a

set encoding=utf-8

